image: openjdk:17-oracle

stages:
  - build
  - test
  - deploy_to_dev
  - deploy_to_test
  - deploy

build:
  stage: build
  script:
    - chmod +x ./mvnw
    - ./mvnw package
  artifacts:
    paths:
      - target/CodeHat-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script:
    - chmod +x ./mvnw
    - ./mvnw test

deploy_to_dev:
  stage: deploy_to_dev
  environment:
    name: dev
  image: ruby:latest
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME_DEV --api-key=$HEROKU_KEY
  only:
    dev

deploy_to_test:
  stage: deploy_to_test
  environment:
    name: test
  image: ruby:latest
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME_TEST --api-key=$HEROKU_KEY
  only:
    - test

deploy:
  stage: deploy
  environment:
    name: production
  image: ruby:latest
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_KEY
  only:
    - main
